[package]
name = "catboost"
version = "0.1.0"
authors = ["Sergey Kiselev <kiselev.sg@gmail.com>"]
edition = "2018"

[dependencies]
catboost-sys = { path = "catboost-sys" }
approx = "0.5.1"

[features]
gpu = ["catboost-sys/gpu"]
